<?php
module_load_include('inc', 'ct_quiz', 'includes/ct_quiz.functions');
/**
 * Implements hook_menu().
 */
function ct_quiz_menu() {

  $items = array();

  $items['quiz'] = array(
    'title' => "Quizzes Landing Page",
    'page callback' => 'ct_quiz_render_spa',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['api/quiz'] = array(
    'access callback' => TRUE,
    'page callback' => 'ct_quiz_api',
    'delivery callback' => 'drupal_json_output',
  );

  return $items;
}

/**
 * Callback to create Quizzes Landing Page.
 */
function ct_quiz_render_spa() {
  $quiz_nodes = published_quiz_nodes();

  return theme(
    'quiz_list', array(
      'quiz_list_nodes' => $quiz_nodes
    )
  );
}

/**
 * Implements hook_theme().
 */
function ct_quiz_theme() {
  $theme_path = drupal_get_path('module', 'ct_quiz') . '/templates';

  return array(
    'quiz_list' => array(
      'variables' => array('quiz_list_nodes' => NULL),
      'template' => 'quiz',
      'path' => $theme_path,
      'type' => 'theme',
    ),
  );
}

/**
 * Implements hook_preprocess_page().
 */
function ct_quiz_preprocess_page() {
  $path = drupal_get_path_alias(current_path());
  $theme_path = drupal_get_path('module', 'ct_quiz');

  if ($path == 'quiz') {
    drupal_add_css($theme_path . '/css/ct_quiz.css');

    drupal_add_js($theme_path . '/js/vue.min.js');
    drupal_add_js($theme_path . '/js/axios.min.js');
    drupal_add_css('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', 'external');
  }
}

/**
 * Callback function to return the data.
 */
function ct_quiz_api() {
  $params = drupal_get_query_parameters();
  $data = array(
    'code' => 1,
    'data' => new stdClass(),
    'message' => 'No results found',
  );
  // Check if param quiz has been obtained.
  if (isset($params['quiz']) && is_numeric($params['quiz'])) {
    $quizId = $params['quiz'];

    if ($node = node_load($quizId)) {
      $data['code'] = 0;
      $data['message'] = 'Node found';
      $data['data']->title = $node->title;

      $items = field_get_items('node', $node, 'field_quiz_q_a');

      // Q & A from field collection to render quiz.
      foreach ($items as $key => $item) {
        $fc = field_collection_field_get_entity($item);
        $data['data']->qa[$key]['field_quiz_fc_question'] = $fc->field_quiz_fc_question['und'][0]['safe_value'];
        $data['data']->qa[$key]['field_quiz_fc_answers'] = $fc->field_quiz_fc_answers['und'];
      }

    }
  }

  return drupal_json_output($data);
}
